import enum



class ConfigObjects(enum.Enum):
    SCHEDULE_LINK = "CONFIG_SCHEDULE_LINK"
    IMPORTANT_DATES_LINK = "CONFIG_IMPORTANT_DATES_LINK"
    TEXTBOOKS_LINK = "CONFIG_TEXTBOOKS_LINK"
    FORCE_NAME = "FORCE_NAME"
    VERBOSE_CHANNEL_NAME = "penis"

