import enum



class ConfigObjects(enum.Enum):
    SCHEDULE_LINK = "CONFIG_SCHEDULE_LINK"
    SCHEDULE_ICAL_LINK = "CONFIG_SCHEDULE_ICAL_LINK"
    IMPORTANT_DATES_LINK = "CONFIG_IMPORTANT_DATES_LINK"
    IMPORTANT_DATES_ICAL_LINK = "CONFIG_IMPORTANT_DATES_ICAL_LINK"
    TEXTBOOKS_LINK = "CONFIG_TEXTBOOKS_LINK"
    FORCE_NAME = "FORCE_NAME"
    VERBOSE_CHANNEL_NAME = "VERBOSE_CHANNEL_NAME"
    UPCOMING_LENGTH = "UPCOMING_LENGTH"
