import enum



class ConfigObjects(enum.Enum):
    SCHEDULE_LINK = "CONFIG_SCHEDULE_LINK"
    SCHEDULE_LINK_ICAL = "CONFIG_SCHEDULE_LINK_ICAL"
    SCHEDULE_LINK_ALT = "CONFIG_SCHEDULE_LINK_ALT"
    SCHEDULE_LINK_ALT_ICAL = "CONFIG_SCHEDULE_LINK_ALT_ICAL"
    IMPORTANT_DATES_LINK = "CONFIG_IMPORTANT_DATES_LINK"
    IMPORTANT_DATES_LINK_EE = "CONFIG_IMPORTANT_DATES_LINK_EE"
    IMPORTANT_DATES_LINK_CE = "CONFIG_IMPORTANT_DATES_LINK_CE"
    TEXTBOOKS_LINK = "CONFIG_TEXTBOOKS_LINK"
    FORCE_NAME = "FORCE_NAME"
    VERBOSE_CHANNEL_NAME = "VERBOSE_CHANNEL_NAME"
    UPCOMING_LENGTH = "UPCOMING_LENGTH"
    LOGGING_CHANNEL_NAME = "LOGGING_CHANNEL_NAME"

